version: '3.8'

services:
  app:
    image: app:latest
    container_name: balanced-money-backend
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy 
    env_file:
      - .env
    restart: always
    volumes:
      - .:/var/www/
    command: npm start
    ports:
      - $NODE_HOST_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQL_HOST
      - DB_USERNAME=$MYSQL_USER
      - DB_PORT=$MYSQL_DOCKER_PORT
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_DATABASE=$MYSQL_DATABASE

  db:
    image: mysql:5.7
    restart: always
    container_name: balanced-money-database
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    healthcheck: # mysql takes a minuite to startup, we need to force the app to wait for that so having  condition:service_healthy on app and a healthcheck here (i think) achieves that.
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

volumes: 
  db:
